---
title: "data_preprocessing"
author: "Thais Minet"
date: "1/26/2018"
output: html_document
---
# Data Processing of RNA seq unnormalized data

### Data Preprocessing
Load utility functions.
```{r}
source("utility.R")
```

Read the data into 2 data frames called gtex and tcga using the `MultiMerge` function from `utility.R`. Then merge them into one 
data frame.
```{r}
data.gtex = MultiMerge("unnormalized/gtex/")
data.tcga = MultiMerge("unnormalized/tcga/")
data.combined = merge(gtex, tcga, by=c('Hugo_Symbol', 'Entrez_Gene_Id'))
```

Remove the `Entrez_Gene_Id` column and set the `Hugo_Symbol` column to be the row names for each data frame.
```{r}
rownames(data.gtex) = data.gtex[,1]
data.gtex[,1:2] = NULL
rownames(data.tcga) = data.tcga[,1]
data.tcga[,1:2] = NULL
rownames(data.combined) = data.combined[,1]
data.combined[,1:2] = NULL
```

Remove rows with means close to 0
```{r}
data.combined.nozero = data.combined[-which(rowMeans(data.combined[,]) <= 0.01), ]

# get gtex and tcga counts
# count.gtex = length(grep("GTEX*", colnames(combined.data.nozero)))
# count.tcga = length(grep("TCGA*", colnames(combined.data.nozero)))
```

PCA
```{r}
# pc.obj = fast.prcomp(t(combined.data.nozero), center = FALSE, scale. = FALSE)
# perc = 100*(pc.obj$sdev)^2 / sum(pc.obj$sdev^2)
```

```{r}

```
